<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>1.6.3</Version>
    <AssemblyVersion>1.6.3.0</AssemblyVersion>
    <FileVersion>1.6.3.0</FileVersion>
    <InformationalVersion>1.6.3</InformationalVersion>
  </PropertyGroup>
</Project>
