<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <Version>1.5.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TreasureChest.Core\TreasureChest.Core.csproj" />
    <ProjectReference Include="..\..\src\TreasureChest.App\TreasureChest.App.csproj" />
  </ItemGroup>
</Project>
